name: Publish Docs
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Asciidoctor image
        run: |
          docker build \
            -t local/asciidoctor \
            -f .github/docker/asciidoctor/Dockerfile .

      - name: Create output directories
        run: |
          mkdir -p public
          mkdir -p public/slides
      
      - name: Build documentation
        run: |
          docker run --rm \
            -v "$PWD":/documents \
            -w /documents \
            local/asciidoctor \
            asciidoctor \
              -r asciidoctor-diagram \
              docs/index.adoc \
              -D public
      
      - name: Build Reveal.js slides
        run: |
          docker run --rm \
            -v "$PWD":/documents \
            -w /documents \
            local/asciidoctor \
            sh -c "
              find docs/slides -name '*.adoc' -exec \
                asciidoctor-revealjs \
                  -r asciidoctor-diagram \
                  {} \
                  -D public/slides \
                \;
            "
      - name: Copy media assets
        run: |
          #cp -r docs/media public/
          cp -r docs/slides/media public/slides/     
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

